version: "3"

# Usage https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/samples/12102-docker-compose/docker-compose.yml

services:
  database:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 51521:1521
      - 55500:5500
    environment:
      - ORACLE_PWD=mysecurepassword
      - ORACLE_CHARACTERSET=AL32UTF8
